version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app  # Montez directorul curent local în container
    environment:
      - FLASK_ENV=development  # Activez hot-reloading în Flask